//! Logical content trees and canonical POSIX pax containers, independent of host paths.

const std = @import("std");
const contracts = @import("contracts");

pub const names = @import("names.zig");
pub const parseTar = @import("parse.zig").parse;
pub const writeTar = @import("write.zig").write;
pub const transform = @import("transform.zig").transform;
pub const merge = @import("transform.zig").merge;
pub const Selection = @import("transform.zig").Selection;
pub const fromEntries = @import("transform.zig").normalize;

pub const Error = error{
    ContentInvalid,
    ContentLimit,
    ContentConflict,
    ContentUnsupported,
    ContentReadFailed,
    ContentWriteFailed,
    Canceled,
    OutOfMemory,
};

/// A durable identity has no process handles or source location.
pub const ContainerRef = struct {
    format: enum { posix_pax_v1 } = .posix_pax_v1,
    sha256: contracts.Digest,
    bytes: u64,
};

/// Borrowed backing storage. Keep bytes or the open file alive while any tree uses it.
pub const Source = union(enum) {
    bytes: []const u8,
    file: struct {
        handle: std.Io.File,
        offset: u64 = 0,
        length: u64,
        cancel: ?*const std.atomic.Value(bool) = null,
    },

    pub fn size(source: Source) u64 {
        return switch (source) {
            .bytes => |bytes| bytes.len,
            .file => |file| file.length,
        };
    }

    pub fn read(source: Source, io: std.Io, offset: u64, out: []u8) Error!void {
        std.debug.assert(out.len <= 64 << 10);
        if (offset > source.size() or out.len > source.size() - offset) {
            return error.ContentInvalid;
        }
        switch (source) {
            .bytes => |bytes| {
                const start = std.math.cast(usize, offset) orelse return error.ContentLimit;
                @memcpy(out, bytes[start..][0..out.len]);
            },
            .file => |file| {
                if (file.cancel) |flag| if (flag.load(.acquire)) return error.Canceled;
                const position = std.math.add(u64, file.offset, offset) catch
                    return error.ContentInvalid;
                const count = file.handle.readPositionalAll(io, out, position) catch
                    return error.ContentReadFailed;
                if (count != out.len) return error.ContentInvalid;
            },
        }
    }
};

pub const Body = struct {
    source: Source = .{ .bytes = "" },
    offset: u64 = 0,
    length: u64 = 0,

    pub fn bytes(value: []const u8) Body {
        return .{ .source = .{ .bytes = value }, .length = value.len };
    }
};

pub const Kind = enum { file, directory, symlink };

pub const Entry = struct {
    path: []const u8,
    kind: Kind = .file,
    mode: u16 = 0o644,
    /// Exact relative UTF-8 readlink text. Validation never rewrites these bytes.
    link_target: []const u8 = "",
    body: Body = .{},
};

/// Metadata belongs to the caller's arena; body sources remain borrowed.
pub const Tree = struct {
    entries: []const Entry,
};

/// Snapshot generated bytes into caller-owned durable storage before publishing its reference.
/// The caller flushes/syncs and seals that storage; a failure never returns an identity.
pub fn freeze(
    io: std.Io,
    body: Body,
    output: *std.Io.Writer,
    limits: contracts.Limits,
) Error!struct { sha256: contracts.Digest, bytes: u64 } {
    std.debug.assert(limits.archive_entry_bytes <= limits.expanded_bytes);
    if (body.length > limits.archive_entry_bytes) return error.ContentLimit;
    if (body.offset > body.source.size() or body.length > body.source.size() - body.offset) {
        return error.ContentInvalid;
    }
    var scratch: [64 << 10]u8 = undefined; // SAFETY: read fills each consumed slice.
    var hash = std.crypto.hash.sha2.Sha256.init(.{});
    var offset: u64 = 0;
    while (offset < body.length) {
        const count = std.math.cast(usize, @min(scratch.len, body.length - offset)) orelse
            return error.ContentLimit;
        const source_offset = std.math.add(u64, body.offset, offset) catch
            return error.ContentInvalid;
        try body.source.read(io, source_offset, scratch[0..count]);
        output.writeAll(scratch[0..count]) catch return error.ContentWriteFailed;
        hash.update(scratch[0..count]);
        offset += count;
    }
    return .{ .sha256 = hash.finalResult(), .bytes = body.length };
}

test {
    _ = @import("content_test.zig");
}
