//! Per-file token/node budget (same metrics as `zig fmt --complexity`).
//! Growth over 10% (and over `min_slack_nodes`) needs the baseline updated in the same commit:
//! `zig build lint:baseline`.

const std = @import("std");
const repo = @import("repo");

pub const baseline_path = "tools/lint/complexity-baseline.zon";
pub const growth_percent = 10;
pub const min_slack_nodes = 40;

pub const Entry = struct {
    path: []const u8,
    tokens: u32,
    nodes: u32,
};

const Baseline = struct {
    files: []const Entry = &.{},
};

fn load(arena: std.mem.Allocator, io: std.Io) !Baseline {
    const bytes = repo.read(arena, io, baseline_path) catch |err| switch (err) {
        error.FileNotFound => return .{},
        else => |e| return e,
    };
    var diagnostics: std.zon.parse.Diagnostics = undefined; // SAFETY: initialized by fromSlice.
    return std.zon.parse.fromSlice(Baseline, .{
        .gpa = arena,
        .arena = arena,
        .source = try arena.dupeSentinel(u8, bytes, 0),
        .diagnostics = &diagnostics,
    });
}

pub fn compare(report: *repo.Report, io: std.Io, measured: []const Entry) !void {
    const baseline = try load(report.arena, io);
    for (measured) |entry| {
        const base = find(baseline.files, entry.path) orelse {
            try report.add("{s}: no complexity baseline (zig build lint:baseline)", .{entry.path});
            continue;
        };
        const allowed = base.nodes + @max(base.nodes * growth_percent / 100, min_slack_nodes);
        if (entry.nodes > allowed) {
            try report.add("{s}: nodes {d} > baseline {d} +{d}%", .{
                entry.path, entry.nodes, base.nodes, growth_percent,
            });
        }
    }
    for (baseline.files) |base| {
        if (find(measured, base.path) == null) try report.add(
            "{s}: stale complexity baseline entry",
            .{base.path},
        );
    }
}

fn find(entries: []const Entry, path: []const u8) ?Entry {
    for (entries) |entry| {
        if (std.mem.eql(u8, entry.path, path)) return entry;
    }
    return null;
}

pub fn write(arena: std.mem.Allocator, io: std.Io, measured: []const Entry) !void {
    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;
    try w.writeAll(
        "// Generated by `zig build lint:baseline`. Review growth in the same commit.\n",
    );
    try w.writeAll(".{\n    .files = .{\n");
    for (measured) |entry| {
        try w.print("        .{{ .path = \"{s}\", .tokens = {d}, .nodes = {d} }},\n", .{
            entry.path, entry.tokens, entry.nodes,
        });
    }
    try w.writeAll("    },\n}\n");
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = baseline_path, .data = out.written() });
}
